In [3]:
import numpy as np
xt=np.array([[1,2,3,4,5]]).T
# xt=np.array([[1,2,3,4,5]])
# print(xt[::2])
y=np.array([[6,7,4,3,2]]).T
a=np.linalg.pinv(np.dot(X.T,X))
b=np.dot(X.T,y)
Te=np.dot(a,b)
print

[[-1.2]
 [ 8. ]]


In [5]:
import numpy as np
def linear_regression(X, y, m_current=0, b_current=0, epochs=5000, gama=0.6,learning_rate=0.0001):
    N =float(len(y))
    xt=np.array(X).T
    y=np.array(X).T
    one=np.ones((xt.shape[0],1))
    X=np.concatenate((xt,one),axis=1)
    a=np.linalg.pinv(np.dot(X.T,X))
    b=np.dot(X.T,y)        
    Te=np.dot(a,b)  
    for i in range(epochs):
        Lamda=1/N * np.dot(X.T,y)
        Te=Te-learning_rate * 
        


In [5]:
X=[[1,2,3,4,5]]
y=[[6,7,4,3,2]]

[[55. 15.]
 [15.  5.]]
[[ 0.1 -0.3]
 [-0.3  1.1]]
[[54.]
 [22.]]
[[-1.2]
 [ 8. ]]


(array([[-1.19999842],
       [ 7.9999943 ]]), 90157)


In [10]:
import numpy as np
xt=np.array([[1,2,3,4]]).T
one=np.ones((xt.shape[0],1))
X=np.concatenate((xt,one),axis=1)
y=np.array([[6,7,4,3]]).T
a=np.dot(X.T,X)
print(a)
a=np.linalg.pinv(np.dot(X.T,X))
b=np.dot(X.T,y)
print(b)
Te=np.dot(a,b)
print(Te)

[[30. 10.]
 [10.  4.]]
[[44.]
 [20.]]
[[-1.2]
 [ 8. ]]


In [8]:
print(29*3-81)

6
